services:
  MyFakeSSH:
    build: .
    image: registry.cn-beijing.aliyuncs.com/licsber/myfakessh:latest
    restart: unless-stopped
    container_name: myfakessh
    command: /log
    volumes:
      - /licsber/docker/myfakessh:/log
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "22:22"
